### ISSUE TITLE
running

### ISSUE THREAD

**Issue by adiyenuubarii** [Nilstrieb/dilaria#1]
how do I run and use this programming language

**Comment by Nilstrieb** [comment]
you better don't since it doesn't really work yet

**Comment by Nilstrieb** [comment]
if you still want to:
[install rust](https://www.rust-lang.org/tools/install)
run `cargo run your-file-name`

**Comment by adiyenuubarii** [comment]
and how do I write code for it?

**Comment by Nilstrieb** [comment]
you just write some code into a file and then run it

but I repeat, don't, even function calls are broken

**Comment by adiyenuubarii** [comment]
lmao alright thanks
